version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      lsp:
        applies-to: version-updates
        patterns:
         - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      vscode:
        applies-to: version-updates
        patterns:
         - "*"
