version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      lsp:
        applies-to: version-updates
        patterns:
         - "*"
        exclude-patterns:
        # don't bundle typos-cli together with other updates
         - "typos-cli"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      vscode:
        applies-to: version-updates
        patterns:
         - "*"
