name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - run: cargo test
    - run: cargo fmt --all -- --check
    - run: cargo clippy
    - name: cargo build
      run: |
        cargo build --release
        mkdir -p bundled
        cp target/release/typos-lsp bundled/
    - run: npm ci
    - name: npm test
      env:
        VSCODE_CLI: 1
      run: |
        sudo apt-get install -y xvfb
        xvfb-run npm test
