name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: typos_cli,typos_lsp

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - run: cargo test
    - run: cargo fmt --all -- --check
    - run: cargo clippy
    - run: cargo build
    - run: npm ci
    - run: npm run lint
    # vscode requires an X Server
    - name: npm test
      run: xvfb-run npm test
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - run: cargo test
