name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:  # so release can depend on CI

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - run: cargo test
    - run: cargo fmt --all -- --check
    - run: cargo clippy
    - run: cargo build
    - run: npm ci
    - name: npm test
      run: |
        mkdir -p bundled
        cp target/debug/typos-lsp bundled/
        # vscode requires an X Server
        xvfb-run npm test
