name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - run: cargo test
    - run: cargo fmt --all -- --check
    - run: cargo clippy
    - name: cargo build
      run: |
        cargo build
        mkdir -p bundled
        cp target/debug/typos-lsp bundled/
    - run: npm ci
    - name: npm test
      # vscode requires an X Server
      run: xvfb-run npm test
